### PR TITLE
Allow install php8

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by snapshotpl** [comment]
Depends on https://github.com/laminas/laminas-diactoros/pull/46

**Comment by acelaya** [comment]
Considering laminas/laminas-diactoros already supports PHP 8, would you be open to merge this?

**Comment by snapshotpl** [comment]
Sure! I have just restart jobs to ensure that everything is green

**Comment by acelaya** [comment]
I see the project actually depends on zendframework/zend-diactoros, not laminas/laminas-diactoros.

The former is no longer maintained, so you need to replace it and change all `use Zend\...` by `use Laminas\...`

**Pull request merged**
